--- #YAML:1.0
name:               PPI-XS-Tokenizer
version:            0.03
abstract:           C++ replaction for the PPI Tokenizer
author:
    - Shmuel Fomberg <semuelf@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::XSpp:  0.06
    PPI:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
